Fix typo in JVMOptions expansion on java call
A curly brace is missing from the JVMOptions array expansion causing
errors such as the following when JVMOptions are in use:

Invalid maximum heap size: -Xmx1G[@]}
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.